apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "scm-common-service.fullname" . }}-cors
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ include "scm-common-service.fullname" . }}
  cors:
    allowOrigins:
      - "*" 
    allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowHeaders:
      - Content-Type
      - Authorization
    exposeHeaders:
      - Content-Length
    maxAge: 86400s
