replicaCount: 1

image:
  repository: skaxcommonagentdevacr.azurecr.io/scm-admin-web
  pullPolicy: IfNotPresent
  tag: dev-20260331.16-594d599

service:
  type: ClusterIP
  port: 3000

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
  - name: eg
    namespace: envoy-gateway-system
  hostnames:
  - admin.scm.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /

backendTrafficPolicy:
  enabled: true
  timeout:
    http:
      requestTimeout: 0s

livenessProbe:
  httpGet:
    path: /healthy
    port: http
readinessProbe:
  httpGet:
    path: /healthy
    port: http

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 384Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

config: []
  #NEXT_PUBLIC_API_BASE_URL: "http://api.scm.local"

nodeSelector: 
  role: devops

hostAliases: []