CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    status VARCHAR(255),
    created_date TIMESTAMP NOT NULL,
    last_modified_date TIMESTAMP NOT NULL,
    CONSTRAINT users_status_check CHECK (status IN ('PENDING', 'ACTIVE', 'INACTIVE'))
);

ALTER TABLE users
    ALTER COLUMN id SET DEFAULT nextval('users_seq');

SELECT setval('users_seq', COALESCE((SELECT MAX(id) FROM users), 0) + 1, false);

CREATE TABLE IF NOT EXISTS sample_mybatis_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
